name: Generate SBOM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '31 9 * * 6'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-sbom:
    name: Codebase SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'code.sbom.json'
          scan-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/code.sbom.json'

  image-sbom:
    name: Docker Image SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t crossfit-timetable .

      - name: Run Trivy on Docker image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'image'
          image-ref: 'crossfit-timetable'
          format: 'github'
          output: 'image.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-sbom-report
          path: '${{ github.workspace }}/image.sbom.json'